### ISSUE TITLE
Not working in botkit 4.5.0

### ISSUE THREAD

**Issue by jatinkksharma** [getforgex/botkit-storage-mysql#10]
I have tried using this with botkit 4.5.0 but it fails with following error:

```
Experienced an error inside the turn handler TypeError: this.storage.read is not a function     
     at Promise.resolve.then (/home/node/app/node_modules/botkit/node_modules/botbuilder-core/lib/botState.js:63:37)
     at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:61) UnhandledPromiseRejectionWarning: TypeError: this.storage.read is not a function
     at Promise.resolve.then (/home/node/app/node_modules/botkit/node_modules/botbuilder-core/lib/botState.js:63:37)
     at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:61) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:61) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by easysoft-mobility** [comment]
Same with me.

**Comment by jatinkksharma** [comment]
@easysoft-mobility   ```botkit-storage-mysql``` only works for version 0.x.x. You should use [botbuilder-storage](https:/www.npmjs.com/search?q=botbuilder-storage) to run boktit on newer versions. FYI botbuilder-storage currently does not support mysql.

**Comment by easysoft-mobility** [comment]
okay, thanks !
